#!/usr/bin/env bash
# gexwheel installer for Linux (bare-metal, systemd user timers).
#
# Run from a clone:
#   ./install.sh
# Or straight from GitHub:
#   curl -fsSL https://raw.githubusercontent.com/nsb1014/gexwheel/main/install.sh | bash
#
# Prompts (input is hidden, never echoed, never logged):
#   - Reddit/PRAW API credentials (optional - ApeWisdom works without them)
#
# Non-interactive use: set GEXWHEEL_PRAW_CLIENT_ID / GEXWHEEL_PRAW_CLIENT_SECRET
# in the environment if using PRAW.
#
# Overridable paths:
#   GEXWHEEL_INSTALL_DIR  (default: ~/.local/share/gexwheel/app)
#   GEXWHEEL_DATA_DIR     (default: ~/gexwheel-data)
set -euo pipefail

REPO_URL="${GEXWHEEL_REPO_URL:-https://github.com/nsb1014/gexwheel.git}"
INSTALL_DIR="${GEXWHEEL_INSTALL_DIR:-$HOME/.local/share/gexwheel/app}"
DATA_DIR="${GEXWHEEL_DATA_DIR:-$HOME/gexwheel-data}"
CONFIG_PATH="$DATA_DIR/config.yaml"
UNIT_DIR="$HOME/.config/systemd/user"

info() { printf '\033[1;34m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33mwarning:\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[1;31merror:\033[0m %s\n' "$*" >&2; exit 1; }

# ---------------------------------------------------------------- prereqs
command -v git >/dev/null     || die "git is required (e.g. sudo apt install git)"
command -v python3 >/dev/null || die "python3 is required (3.10+)"
python3 - <<'PY' || die "python 3.10+ is required"
import sys; sys.exit(0 if sys.version_info >= (3, 10) else 1)
PY
python3 -c 'import ensurepip' 2>/dev/null \
    || die "python venv support is missing (e.g. sudo apt install python3-venv)"

# Interactive prompts must come from the real terminal even under `curl | bash`.
TTY=""
if [ -t 0 ]; then
    TTY=/dev/stdin
elif [ -e /dev/tty ] && (exec </dev/tty) 2>/dev/null; then
    TTY=/dev/tty
fi

prompt_hidden() { # $1=prompt text -> echoes value
    local value=""
    [ -n "$TTY" ] || return 0
    # shellcheck disable=SC2162
    read -s -p "$1" value <"$TTY" >/dev/tty 2>&1 || true
    printf '\n' >/dev/tty
    printf '%s' "$value"
}

prompt_plain() { # $1=prompt text, $2=default -> echoes value
    local value=""
    if [ -n "$TTY" ]; then
        read -r -p "$1" value <"$TTY" >/dev/tty 2>&1 || true
    fi
    printf '%s' "${value:-$2}"
}

# ---------------------------------------------------------------- code
if [ -n "${BASH_SOURCE[0]:-}" ] && [ -f "${BASH_SOURCE[0]}" ] \
   && [ -f "$(dirname "${BASH_SOURCE[0]}")/src/gexwheel/__main__.py" ]; then
    INSTALL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    info "Installing from existing checkout: $INSTALL_DIR"
elif [ -d "$INSTALL_DIR/.git" ]; then
    info "Updating existing install in $INSTALL_DIR"
    git -C "$INSTALL_DIR" pull --ff-only
else
    info "Cloning $REPO_URL -> $INSTALL_DIR"
    mkdir -p "$(dirname "$INSTALL_DIR")"
    git clone --depth 1 "$REPO_URL" "$INSTALL_DIR"
fi

# ---------------------------------------------------------------- venv
VENV="$INSTALL_DIR/.venv"
info "Creating virtualenv and installing dependencies"
python3 -m venv "$VENV"
"$VENV/bin/pip" install --quiet --upgrade pip
"$VENV/bin/pip" install --quiet -r "$INSTALL_DIR/requirements.txt"

# ---------------------------------------------------------------- config
mkdir -p "$DATA_DIR"

if [ -f "$CONFIG_PATH" ]; then
    info "Keeping existing config: $CONFIG_PATH (delete it and re-run to reconfigure)"
else
    PRAW_ID="${GEXWHEEL_PRAW_CLIENT_ID:-}"
    PRAW_SECRET="${GEXWHEEL_PRAW_CLIENT_SECRET:-}"
    if [ -z "$PRAW_ID" ] && [ -n "$TTY" ]; then
        ANSWER="$(prompt_plain "Configure Reddit/PRAW API credentials? Optional - ApeWisdom needs no key. [y/N] " "n")"
        case "$ANSWER" in
            y|Y|yes|YES)
                PRAW_ID="$(prompt_hidden "PRAW client id (input hidden): ")"
                PRAW_SECRET="$(prompt_hidden "PRAW client secret (input hidden): ")"
                ;;
        esac
    fi

    info "Writing $CONFIG_PATH"
    umask 077
    GEXWHEEL_PRAW_CLIENT_ID="$PRAW_ID" \
    GEXWHEEL_PRAW_CLIENT_SECRET="$PRAW_SECRET" \
    GEXWHEEL_DB_PATH="$DATA_DIR/gexwheel.db" \
    "$VENV/bin/python" - "$INSTALL_DIR/config/config.example.yaml" "$CONFIG_PATH" <<'PY'
import os, sys
import yaml

src, dst = sys.argv[1], sys.argv[2]
with open(src) as f:
    cfg = yaml.safe_load(f)

cfg["db_path"] = os.environ["GEXWHEEL_DB_PATH"]

praw_id = os.environ.get("GEXWHEEL_PRAW_CLIENT_ID", "")
praw_secret = os.environ.get("GEXWHEEL_PRAW_CLIENT_SECRET", "")
if praw_id and praw_secret:
    cfg["reddit"]["praw"]["client_id"] = praw_id
    cfg["reddit"]["praw"]["client_secret"] = praw_secret
    cfg["reddit"]["source"] = "both"  # ApeWisdom first, PRAW fallback

with open(dst, "w") as f:
    f.write("# gexwheel configuration - generated by install.sh\n")
    f.write("# All tunables are documented in config/config.example.yaml.\n")
    yaml.safe_dump(cfg, f, sort_keys=False, default_flow_style=False)
PY
    chmod 600 "$CONFIG_PATH"
fi

# ---------------------------------------------------------------- systemd
if command -v systemctl >/dev/null && systemctl --user show-environment >/dev/null 2>&1; then
    info "Installing systemd user units"
    mkdir -p "$UNIT_DIR"
    for job in mentions morning; do
        case "$job" in
            mentions) DESC="gexwheel - daily Reddit mention scan" ;;
            morning)  DESC="gexwheel - weekday pre-market GEX screen + trade identification" ;;
        esac
        cat > "$UNIT_DIR/gexwheel-$job.service" <<UNIT
[Unit]
Description=$DESC
After=network-online.target
Wants=network-online.target

[Service]
Type=oneshot
Environment=PYTHONPATH=$INSTALL_DIR/src
Environment=GEXWHEEL_CONFIG=$CONFIG_PATH
WorkingDirectory=$INSTALL_DIR
ExecStart=$VENV/bin/python -m gexwheel $job

[Install]
WantedBy=default.target
UNIT
        cp "$INSTALL_DIR/deploy/gexwheel-$job.timer" "$UNIT_DIR/"
    done
    systemctl --user daemon-reload
    systemctl --user enable --now gexwheel-mentions.timer gexwheel-morning.timer
    if command -v loginctl >/dev/null; then
        loginctl enable-linger "$USER" 2>/dev/null \
            || warn "could not enable lingering - timers stop when you log out (run: loginctl enable-linger $USER)"
    fi
    SYSTEMD_OK=1
else
    warn "no systemd user session detected - skipping timer setup"
    warn "schedule these yourself (e.g. cron): see deploy/INSTALL.md"
    SYSTEMD_OK=0
fi

# ---------------------------------------------------------------- wrap-up
info "Install complete."
echo
echo "  code:    $INSTALL_DIR"
echo "  config:  $CONFIG_PATH   (chmod 600 - keep private)"
echo "  data:    $DATA_DIR/gexwheel.db"
if [ "$SYSTEMD_OK" = 1 ]; then
    echo "  timers:  gexwheel-mentions.timer (daily 07:00 ET)"
    echo "           gexwheel-morning.timer  (Mon-Fri 07:15 ET)"
fi
echo
